
[build]
  case_sensitive = false


[[redirects]]
  from = "/api/*"
  to = "https://my-netlify-site.netlify.app/:splat"
  status = 200

[build.environment]
  NEXT_PUBLIC_PUBLIC_URL = "https://my-netlify-site.netlify.app"

[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"